language: c
sudo: required
env:
  - OCAML_VERSION=4.04
os:
  - linux
before_install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
install: 
  - sh .travis-ocaml.sh
script: 
  - make test
